baseURL = 'https://robertozanolli.github.io/blog/'
languageCode = 'en-us'
title = 'what i learned today'
theme = 'custom'
publishDir = '../blog'

[outputs]
  home = ['HTML', 'RSS', 'JSON']
[pagination]
  pagerSize = 3  
[params]
  description = "things I learn as a software engineer"
[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    style = 'fruity'
    lineNos = false
    lineNumbersInTable = false
